### ISSUE TITLE
bits-service-release 2.1.0 not published on bosh.io

### ISSUE THREAD

**Issue by petergtz** [bosh-io/releases#44]
Hi,

We recently published version [bits-service-release 2.1.0](https://github.com/cloudfoundry-incubator/bits-service-release/releases/tag/2.1.0) (where before we were at 1.9.0). But the 2.1.0 release never made it to http://bosh.io/releases/github.com/cloudfoundry-incubator/bits-service-release?all=1

What do we need to do to publish this on bosh.io?

Thanks,
Peter

**Comment by mikexuu** [comment]
Hi @petergtz ,

Bosh.io pulls new release versions from the `releases` directory in your default branch. We took a look at your release, and it seems like 2.1.0 was published on `bitsgo` branch. Is this intentional and are y'all trying to switch to `bitsgo` from now on that we need to change which branch bosh.io looks at?

Thanks,
@dpb587-pivotal && @mikexuu

**Comment by petergtz** [comment]
Hi @dpb587-pivotal && @mikexuu,

Yes, it was intentional that this release was built from `bitsgo`. Ideally, we'd like to be able to publish 1.x releases from `master` and 2.x from `bitsgo`.

But for now it would be cool if you could just switch the branch to `bitsgo`. (We're not even sure if we'll make another 1.x release).

Thanks,
Peter

**Comment by petergtz** [comment]
Never mind guys, we are publishing this stuff now on our master branch. Closing.
